package grammar

// This file holds the canonical English name and a one-line meaning for
// every grammatical abbreviation used in Ithkuil V4 formatives. Sourced
// from docs/reference/morphology.md.
//
// Used by the compose package (to make grammar searches respond to
// "ergative", "solicitative", etc.) and by the inspect/analyze layer
// (to translate the per-slot codes for learners).

// Name returns the canonical English name for an abbreviation
// ("Ergative" for "ERG"). Returns "" when the abbreviation is unknown.
func Name(abbrev string) string { return canonicalNames[abbrev] }

// Meaning returns a one-line description of the grammatical value
// behind an abbreviation. May be empty when no meaning is recorded.
func Meaning(abbrev string) string { return meanings[abbrev] }

// AllNamed returns every (abbrev, name) pair as it appears in the
// canonical-names table. Order is not specified.
func AllNamed() map[string]string {
	out := make(map[string]string, len(canonicalNames))
	for k, v := range canonicalNames {
		out[k] = v
	}
	return out
}

var canonicalNames = map[string]string{
	// Stem
	"S0": "Stem 0",
	"S1": "Stem 1",
	"S2": "Stem 2",
	"S3": "Stem 3",
	// Version
	"PRC": "Processual",
	"CPT": "Completive",
	// Function
	"STA": "Static",
	"DYN": "Dynamic",
	// Specification
	"BSC": "Basic",
	"CTE": "Contential",
	"CSV": "Constitutive",
	"OBJ": "Objective",
	// Context
	"EXS": "Existential",
	"FNC": "Functional",
	"RPS": "Representational",
	"AMG": "Amalgamative",
	// Configuration
	"UPX": "Uniplex",
	"DPX": "Duplex",
	"DSS": "Duplex Similar Separate",
	"DSC": "Duplex Similar Connected",
	"DSF": "Duplex Similar Fused",
	"DDS": "Duplex Dissimilar Separate",
	"DDC": "Duplex Dissimilar Connected",
	"DDF": "Duplex Dissimilar Fused",
	"DFS": "Duplex Fuzzy Separate",
	"DFC": "Duplex Fuzzy Connected",
	"DFF": "Duplex Fuzzy Fused",
	"MSS": "Multiplex Similar Separate",
	"MSC": "Multiplex Similar Connected",
	"MSF": "Multiplex Similar Fused",
	"MDS": "Multiplex Dissimilar Separate",
	"MDC": "Multiplex Dissimilar Connected",
	"MDF": "Multiplex Dissimilar Fused",
	"MFS": "Multiplex Fuzzy Separate",
	"MFC": "Multiplex Fuzzy Connected",
	"MFF": "Multiplex Fuzzy Fused",
	// Affiliation
	"CSL": "Consolidative",
	"ASO": "Associative",
	"COA": "Coalescent",
	"VAR": "Variative",
	// Perspective
	"M": "Monadic",
	"G": "Agglomerative",
	"N": "Nomic",
	"A": "Abstract",
	// Extension
	"DEL": "Delimitive",
	"PRX": "Proximal",
	"ICP": "Inceptive",
	"ATV": "Attenuative",
	"GRA": "Graduative",
	"DPL": "Depletive",
	// Essence
	"NRM": "Normal",
	"RPV": "Representative",
	// Valence
	"MNO": "Monoactive",
	"PRL": "Parallel",
	"CRO": "Corollary",
	"RCP": "Reciprocal",
	"CPL": "Complementary",
	"DUP": "Duplicative",
	"DEM": "Demonstrative",
	"CNG": "Contingent",
	"PTI": "Participative",
	// Phase
	"PCT": "Punctual",
	"ITR": "Iterative",
	"REP": "Repetitive",
	"ITM": "Intermittent",
	"RCT": "Recurrent",
	"FRE": "Frequentative",
	"FRG": "Fragmentative",
	"VAC": "Vacillative",
	"FLC": "Fluctuative",
	// Effect
	"BEN1": "Beneficial to speaker",
	"BEN2": "Beneficial to addressee",
	"BEN3": "Beneficial to 3rd party",
	"BSLF": "Beneficial to self",
	"UNK":  "Unknown",
	"DSLF": "Detrimental to self",
	"DET3": "Detrimental to 3rd party",
	"DET2": "Detrimental to addressee",
	"DET1": "Detrimental to speaker",
	// Level
	"MIN": "Minimal",
	"SBE": "Subequative",
	"IFR": "Inferior",
	"DFT": "Deficient",
	"EQU": "Equative",
	"SUR": "Surpassive",
	"SPL": "Superlative",
	"SPQ": "Superequative",
	"MAX": "Maximal",
	// Aspect
	"RTR": "Retrospective",
	"PRS": "Prospective",
	"HAB": "Habitual",
	"PRG": "Progressive",
	"IMM": "Imminent",
	"PCS": "Precessive",
	"REG": "Regulative",
	"SMM": "Summative",
	"ATP": "Anticipatory",
	"RSM": "Resumptive",
	"CSS": "Cessative",
	"PAU": "Pausal",
	"RGR": "Regressive",
	"PCL": "Preclusive",
	"CNT": "Continuative",
	"ICS": "Incessative",
	"EXP": "Experiential",
	"IRP": "Interruptive",
	"PMP": "Preemptive",
	"CLM": "Climactic",
	"DLT": "Dilatory",
	"TMP": "Temporary",
	"XPD": "Expenditive",
	"LIM": "Limitative",
	"EPD": "Expeditive",
	"PTC": "Protractive",
	"PPR": "Preparatory",
	"DCL": "Disclusive",
	"CCL": "Conclusive",
	"CUL": "Culminative",
	"IMD": "Intermediative",
	"TRD": "Tardative",
	"TNS": "Transitional",
	"ITC": "Intercommutative",
	"MTV": "Motive",
	"SQN": "Sequential",
	// Mood
	"FAC": "Factual",
	"SUB": "Subjunctive",
	"ASM": "Assumptive",
	"SPC": "Speculative",
	"COU": "Counterfactive",
	"HYP": "Hypothetical",
	// Case-Scope
	"CCN": "Natural case-scope",
	"CCA": "Antecedent case-scope",
	"CCS": "Subaltern case-scope",
	"CCQ": "Qualifier case-scope",
	"CCP": "Precedent case-scope",
	"CCV": "Successive case-scope",
	// Illocution
	"ASR": "Assertive",
	"DIR": "Directive",
	"DEC": "Declarative",
	"IRG": "Interrogative",
	"VER": "Verificative",
	"ADM": "Admonitive",
	"POT": "Potentiative",
	"HOR": "Hortative",
	"CNJ": "Conjectural",
	// Validation
	"OBS": "Observational",
	"REC": "Recollective",
	"PUP": "Purportive",
	"RPR": "Reportive",
	"USP": "Unspecified",
	"IMA": "Imaginary",
	"CVN": "Conventional",
	"ITU": "Intuitive",
	"INF": "Inferential",
	// Case (68 entries)
	"THM": "Thematic",
	"INS": "Instrumental",
	"ABS": "Absolutive",
	"AFF": "Affective",
	"STM": "Stimulative",
	"EFF": "Effectuative",
	"ERG": "Ergative",
	"DAT": "Dative",
	"IND": "Inducive",
	"POS": "Possessive",
	"PRP": "Proprietive",
	"GEN": "Genitive",
	"ATT": "Attributive",
	"PDC": "Productive",
	"ITP": "Interpretive",
	"OGN": "Originative",
	"IDP": "Interdependent",
	"PAR": "Partitive",
	"APL": "Applicative",
	"PUR": "Purposive",
	"TRA": "Transmissive",
	"DFR": "Deferential",
	"CRS": "Contrastive",
	"TSP": "Transpositive",
	"CMM": "Commutative",
	"CMP": "Comparative",
	"CSD": "Considerative",
	"FUN": "Functive",
	"TFM": "Transformative",
	"CLA": "Classificative",
	"RSL": "Resultative",
	"CSM": "Consumptive",
	"CON": "Concessive",
	"AVR": "Aversive",
	"CVS": "Conversive",
	"SIT": "Situative",
	"PRN": "Pertinential",
	"DSP": "Descriptive",
	"COR": "Correlative",
	"CPS": "Compositive",
	"COM": "Comitative",
	"UTL": "Utilitative",
	"PRD": "Predicative",
	"RLT": "Relative",
	"ACT": "Activative",
	"ASI": "Assimilative",
	"ESS": "Essive",
	"TRM": "Terminative",
	"SEL": "Selective",
	"CFM": "Conformative",
	"DEP": "Dependent",
	"VOC": "Vocative",
	"LOC": "Locative",
	"ATD": "Attendant",
	"ALL": "Allative",
	"ABL": "Ablative",
	"ORI": "Orientative",
	"IRL": "Interrelative",
	"INV": "Intrative",
	"NAV": "Navigative",
	"CNR": "Concursive",
	"ASS": "Assessive",
	"PER": "Periodic",
	"PRO": "Prolapsive",
	"PCV": "Precursive",
	"PCR": "Postcursive",
	"ELP": "Elapsive",
	"PLM": "Prolimitive",
	// Bias
	"DOL": "Dolorous",
	"DIS": "Dismissive",
	"DRS": "Derisive",
	"PES": "Pessimistic",
	"DUB": "Dubitative",
	"SKP": "Skeptical",
	"TRP": "Trepidative",
	"APH": "Apprehensive",
	"IPT": "Impatient",
	"ANP": "Anticipative",
	"DPB": "Disapprobative",
	"CTP": "Contemptive",
	"IDG": "Indignative",
	"EXA": "Exasperative",
	"RPU": "Repulsive",
	"IVD": "Invidious",
	"VEX": "Vexative",
	"STU": "Stupefactive",
	"PPX": "Perplexive",
	"DCC": "Disconcertive",
	"RVL": "Revelative",
	"FSC": "Fascinative",
	"EUH": "Euphoric",
	"GRT": "Gratificative",
	"SAT": "Satiative",
	"DLC": "Delectative",
	"IFT": "Infatuative",
	"SOL": "Solicitative",
	"RAC": "Reactive",
	"MAN": "Mandatory",
	"EXG": "Exigent",
	"ATE": "Attentive",
	"APB": "Approbative",
	"OPT": "Optimal",
	"CNV": "Contensive",
	"ACC": "Accidental",
	"ACH": "Archetypal",
	"IRO": "Ironic",
	"PSM": "Presumptive",
	"CRR": "Corrective",
	"EUP": "Euphemistic",
	"PSC": "Prosaic",
	"CMD": "Comedic",
	"PPV": "Propositive",
	"SGS": "Suggestive",
	"DFD": "Diffident",
	"RFL": "Reflective",
	"DES": "Desperative",
	"COI": "Coincidental",
	"FOR": "Fortuitous",
	"ANN": "Annunciative",
	"RSG": "Resignative",
	"ISP": "Insipid",
	"IPL": "Implicative",
	"MNF": "Manifestive",
	"ARB": "Arbitrary",
	"PPT": "Propitious",
	"CTV": "Contemplative",
	"CRP": "Corruptive",
	"DEJ": "Dejective",
	"ADS": "Admissive",
	// Register
	"NRR": "Narrative",
	"DSV": "Discursive",
	"PNT": "Parenthetical",
	"SPF": "Specificative",
	"EXM": "Exemplificative",
	"CGT": "Cogitant",
	"END": "End of register",
}

// meanings holds short one-line descriptions for the most-asked-about
// values. Empty entries are fine; the analyze output falls back to the
// canonical name alone.
var meanings = map[string]string{
	// Stem / Version
	"S0":  "basic / generic stem",
	"S1":  "first specialization",
	"S2":  "second specialization",
	"S3":  "third specialization",
	"PRC": "the act/state as a process",
	"CPT": "the completed act/state",
	// Function
	"STA": "entity as a state, condition, or quality",
	"DYN": "entity as a dynamic event or action",
	// Specification
	"BSC": "holistic instantiation, prior to other specifications",
	"CTE": "content/essence/function vs. mere form",
	"CSV": "form/shape vs. functional content",
	"OBJ": "tangible tool/object/patient associated with the act/state",
	// Context
	"EXS": "pure existence (default ontology)",
	"FNC": "functional context (purpose, role)",
	"RPS": "representational context (model, symbol)",
	"AMG": "amalgamative context (blended/composite)",
	// Affiliation
	"CSL": "no specific affiliation among members",
	"ASO": "members share a common purpose",
	"COA": "members combine into a single function",
	"VAR": "members serve diverse, contrasting roles",
	// Perspective
	"M": "single instance/individual",
	"G": "fuzzy number (one or more)",
	"N": "generic / archetypal class",
	"A": "abstract concept / idea",
	// Extension
	"DEL": "default — bounded, demarcated",
	"PRX": "current / ongoing instance",
	"ICP": "the beginning / inception",
	"ATV": "the conclusion / wind-down",
	"GRA": "gradual transition into being",
	"DPL": "gradual transition out of being",
	// Essence
	"NRM": "the entity as it actually exists",
	"RPV": "the entity as imagined/representative",
	// Valence — how multiple participants relate in the event
	"MNO": "one participant; no co-actor (default)",
	"PRL": "two or more parallel co-actors doing the same action",
	"CRO": "one party's action is a corollary of another's",
	"RCP": "mutual / reciprocal action between parties",
	"CPL": "complementary actions, each completing the other",
	"DUP": "duplicative — same action repeated in parallel",
	"DEM": "demonstrative — one party shows another how",
	"CNG": "contingent — one action depends on another",
	"PTI": "participative — taking part in a wider group action",
	// Phase — how the event unfolds in time
	"PCT": "punctual / momentary",
	"ITR": "iterative — happens again and again",
	"REP": "repetitive — same identical instances",
	"ITM": "intermittent — on and off",
	"RCT": "recurrent — returns periodically",
	"FRE": "frequentative — happens often",
	"FRG": "fragmentative — broken into pieces",
	"VAC": "vacillative — alternating, wavering",
	"FLC": "fluctuative — irregularly varying",
	// Effect — beneficial / detrimental impact
	"BEN1": "beneficial to the speaker",
	"BEN2": "beneficial to the addressee",
	"BEN3": "beneficial to an unspecified third party",
	"BSLF": "beneficial to the subject itself",
	"UNK":  "neutral / unknown effect",
	"DSLF": "detrimental to the subject itself",
	"DET3": "detrimental to an unspecified third party",
	"DET2": "detrimental to the addressee",
	"DET1": "detrimental to the speaker",
	// Level — degree of comparison against a reference
	"MIN": "the minimum / least",
	"SBE": "below the reference",
	"IFR": "inferior to the reference",
	"DFT": "deficient — falling short",
	"EQU": "equal to the reference",
	"SUR": "surpassing the reference",
	"SPL": "superlative — the most",
	"SPQ": "superequative — far exceeding",
	"MAX": "the maximum / greatest",
	// Cases (68 total, ordered per §3.9.1)
	// Transrelative (1–9)
	"THM": "inactive participant (CONTENT role)",
	"INS": "INSTRUMENT used by an agent",
	"ABS": "PATIENT undergoing the act",
	"AFF": "EXPERIENCER of unwilled experience",
	"STM": "STIMULUS triggering an affective response",
	"EFF": "ENABLER initiating a causal chain",
	"ERG": "AGENT or FORCE that causes the act",
	"DAT": "RECIPIENT of transference/communication",
	"IND": "self-acting AGENT+PATIENT",
	// Appositive (10–18)
	"POS": "alienable possessor (circumstantial)",
	"PRP": "owner (long-term possessor)",
	"GEN": "inalienable possessor / intrinsic attribute",
	"ATT": "attribute or characteristic of",
	"PDC": "creator / author / originator",
	"ITP": "subjective viewpoint through which X is interpreted",
	"OGN": "original source or native location",
	"IDP": "complementary / mutually dependent counterpart",
	"PAR": "quantitative content — \"a cup of X\"",
	// Associative (19–27)
	"APL": "circumstantial use or function of X",
	"PUR": "inherent purpose — \"for the purpose of\"",
	"TRA": "beneficiary or recipient of harm",
	"DFR": "for X's sake / out of deference to X",
	"CRS": "instead of / in place of X",
	"TSP": "on behalf of X",
	"CMM": "in exchange for X",
	"CMP": "as compared to / versus / whereas",
	"CSD": "according to / as per X",
	// Adverbial (28–36)
	"FUN": "the manner in which X is/occurs",
	"TFM": "into — the final state of a transformation",
	"CLA": "basis for arranging / sorting / counting",
	"RSL": "result or consequence of X",
	"CSM": "resource consumed in the process",
	"CON": "despite / in spite of / although",
	"AVR": "for fear of / in order to avoid",
	"CVS": "except for / unless / but for",
	"SIT": "given / because of / in view of",
	// Relational (37–44)
	"PRN": "about / regarding / concerning",
	"DSP": "describing — like X qualitatively",
	"COR": "in relation to / in association with",
	"CPS": "made of / composed of X",
	"COM": "along with / accompanied by",
	"UTL": "while using or wielding X",
	"PRD": "based on / dependent on X",
	"RLT": "marks a relative clause",
	// Affinitive (45–52)
	"ACT": "experiencer of a modal state (want, need, ability)",
	"ASI": "as if it were X (analogy / metaphor)",
	"ESS": "as X (functional identity or role)",
	"TRM": "goal of an act — toward / for",
	"SEL": "every X / on Xs (recurring entity or period)",
	"CFM": "pursuant to / in conformance with X",
	"DEP": "contingent on X (if circumstances allow)",
	"VOC": "noun used in direct address",
	// Spatio-Temporal I (53–60)
	"LOC": "location at / in / on / by",
	"ATD": "in the presence of X (witness, peripheral party)",
	"ALL": "moving toward",
	"ABL": "moving away from",
	"ORI": "X's face / front / forward axis",
	"IRL": "relative to X (directional or temporal position)",
	"INV": "since / until / from X (boundary of a span)",
	"NAV": "along X (X's axis as direction)",
	// Spatio-Temporal II (61–68)
	"CNR": "at or during the time of X (temporal locative)",
	"ASS": "per X (increment for a ratio)",
	"PER": "within / over X (time span for repetitions)",
	"PRO": "for X (duration of an act)",
	"PCV": "before X (point in time prior)",
	"PCR": "after X (point in time subsequent)",
	"ELP": "X ago / X from now",
	"PLM": "by X / within X (deadline)",
	// Aspect (top picks)
	"RTR": "has been / has done",
	"PRS": "is going to / about to",
	"HAB": "habitually",
	"PRG": "in progress / currently",
	"IMM": "imminent — about to start",
	"PCS": "just finished / just before",
	"REG": "happens at regular intervals",
	"SMM": "have already done",
	"ATP": "have yet to — not yet",
	"RSM": "resumed after a pause",
	"CSS": "ceased / stopped",
	"PAU": "paused, waiting to continue",
	"RGR": "going backward / undoing",
	"PCL": "precluded from happening",
	"CNT": "continuing",
	"ICS": "happens ceaselessly",
	"EXP": "experiential — has experienced",
	"IRP": "interrupted partway",
	"PMP": "preemptive — before another can",
	"CLM": "climactic — peak moment",
	"DLT": "long-delayed",
	"TMP": "temporary",
	"XPD": "expended / used up",
	"LIM": "limitative — just in time",
	"EPD": "expeditive — promptly",
	"PTC": "protractive — taking one's time",
	"PPR": "preparatory — in preparation",
	"DCL": "disclusive — without doing",
	"CCL": "conclusive — finally",
	"CUL": "culminative — having reached completion",
	"IMD": "intermediative — in between",
	"TRD": "tardative — late, delayed",
	"TNS": "transitional",
	"ITC": "intercommutative — back and forth",
	"MTV": "motive — out of habit/inclination",
	"SQN": "sequential — one after another",
	// Mood
	"FAC": "factual — actually the case",
	"SUB": "subjunctive — possibly the case",
	"ASM": "assumptive — assumed/presumed",
	"SPC": "speculative — guessed",
	"COU": "counterfactive — would have been",
	"HYP": "hypothetical — imagined",
	// Case-Scope
	"CCN": "default — case follows clause head or main verb",
	"CCA": "head — governs case of clause's unmarked nouns",
	"CCS": "head — paired with CCQ qualifier(s)",
	"CCQ": "qualifier — modifies a CCS head",
	"CCP": "scope over next formative only",
	"CCV": "scope over previous formative only",
	// Illocution
	"ASR": "I assert / state",
	"DIR": "I direct / command",
	"DEC": "I declare (performative)",
	"IRG": "I ask",
	"VER": "I ask for confirmation (yes/no question)",
	"ADM": "I warn / advise against",
	"POT": "I wish / hope (unrealized)",
	"HOR": "I wish it were so (counterfactual)",
	"CNJ": "I conjecture",
	// Validation (basis for an ASR claim)
	"OBS": "present sensory knowledge — I perceive / I know",
	"REC": "past sensory memory — I remember",
	"PUP": "from a verifiable source — I've read / an expert says",
	"RPR": "hearsay — I heard / someone says",
	"USP": "validation deliberately unspecified",
	"IMA": "unreal — imagination, dream, fantasy",
	"CVN": "shared cultural knowledge — they say / it is said",
	"ITU": "intuition / hunch — I feel / something tells me",
	"INF": "inferred from evidence — I infer / I reason",
	// Bias (60 values per §4.7, English-style interjections)
	"ACC": "as luck would have it / what luck!",
	"ACH": "what a...! / boy, did X ever...!",
	"ADS": "mm-hm / uh-huh (acknowledged without assent)",
	"ANN": "guess what! / wait till you hear this!",
	"ANP": "I'm looking forward to this!",
	"APB": "that's OK / fine / sure",
	"APH": "I'm worried / I've got a bad feeling",
	"ARB": "whatever / ah, what the hell",
	"ATE": "well, whaddya know / look at that",
	"CMD": "funny! / LOL",
	"CNV": "I told you so / you see?!",
	"COI": "what a coincidence!",
	"CRP": "how corrupt! / what corruption!",
	"CRR": "that is to say... / what I mean is...",
	"CTP": "what nonsense! / what bullshit!",
	"CTV": "I wonder... / hmm...",
	"DCC": "I'm not sure about this / out of my element",
	"DEJ": "(sigh) — dejection / disillusionment",
	"DES": "I'm afraid... / I don't know how to say this",
	"DFD": "sorry, but... / it's nothing, just...",
	"DIS": "is that it? / big deal / so what?",
	"DLC": "whee!",
	"DOL": "ow! / ouch!",
	"DPB": "I don't like... / unacceptable!",
	"DRS": "how foolish / silly / ridiculous!",
	"DUB": "hmm, not likely / I doubt it",
	"EUH": "(sigh) what bliss!",
	"EUP": "let's just say... / let me put it this way...",
	"EXA": "dammit! / don't you get it?",
	"EXG": "it's now or never!",
	"FOR": "it's just as well / all's well that ends well",
	"FSC": "cool! / wow! / awesome!",
	"GRT": "ah, what bliss! (physical pleasure)",
	"IDG": "the nerve! / how dare...!",
	"IFT": "praise be! / thank God for...!",
	"IPL": "of course / after all / needless to say",
	"IPT": "c'mon! / what're you waiting for?",
	"IRO": "oh, nice! / just great! (sarcastic)",
	"ISP": "meh (uninterested) / how boring!",
	"IVD": "why does X get to and I don't?! / how unfair!",
	"MAN": "take it or leave it / this is your last chance",
	"MNF": "ah! / well, now! / so!",
	"OPT": "\"so\" / \"totally\" — emphatic intensifier",
	"PES": "yeah, like it really matters / pfft",
	"PPT": "it's a wonder that...",
	"PPV": "what if... / consider this / posit that...",
	"PPX": "huh?! / WTF? / you gotta be kidding!",
	"PSC": "meh (disappointed) / how ordinary!",
	"PSM": "it can only mean one thing / and that's that!",
	"RAC": "my goodness! / wow! / amazing!",
	"RFL": "as I see it / in my opinion",
	"RPU": "yuck! / ew! / how gross!",
	"RSG": "so much for...! / there goes...!",
	"RVL": "no wonder! / so that's why! / a-ha!",
	"SAT": "how satisfying! / at last! (emotional pleasure)",
	"SGS": "how about... / we could... / might I suggest...",
	"SKP": "yeah, right! / like anyone'd believe that!",
	"SOL": "please",
	"STU": "woah! / what the...! / holy...!",
	"TRP": "oh God / oh no / oh dear (fear)",
	"VEX": "how annoying! / what a pain!",
	// Register
	"NRR": "narration (default)",
	"DSV": "direct speech (quotation)",
	"PNT": "aside / parenthetical",
	"SPF": "proper name",
	"EXM": "giving an example",
	"CGT": "internal thought",
	"END": "ends the open register",
	// Configuration — matrix of Plexity × Similarity × Separability
	"UPX": "a single instance",
	"DPX": "two instances forming one entity",
	"DSS": "two similar instances, separate",
	"DSC": "two similar instances, connected",
	"DSF": "two similar instances, fused",
	"DDS": "two dissimilar instances, separate",
	"DDC": "two dissimilar instances, connected",
	"DDF": "two dissimilar instances, fused",
	"DFS": "two instances of indeterminate similarity, separate",
	"DFC": "two instances of indeterminate similarity, connected",
	"DFF": "two instances of indeterminate similarity, fused",
	"MSS": "three or more similar instances, separate",
	"MSC": "three or more similar instances, connected",
	"MSF": "three or more similar instances, fused",
	"MDS": "three or more dissimilar instances, separate",
	"MDC": "three or more dissimilar instances, connected",
	"MDF": "three or more dissimilar instances, fused",
	"MFS": "three or more instances of indeterminate similarity, separate",
	"MFC": "three or more instances of indeterminate similarity, connected",
	"MFF": "three or more instances of indeterminate similarity, fused",
}
