package phonology

import "strings"

// rootConjunctRows is the whole of §§9-11: the tri-, tetra- and
// penta-consonantal conjuncts that may be a C_R root or a C_S affix.
// Each row gives a set of permitted consonants per position, and every
// combination of them is one permissible conjunct.
//
// Held as rows rather than expanded into a set. The expansion is some
// five thousand strings and would be built at init in every binary that
// links this package, including the browser one; scanning 626 rows is
// cheaper than that and costs nothing at startup.
//
// Transcribed from docs/reference/phonotactics.md and checked against it
// by TestRootConjunctRows_MatchTheDocument, so the document stays the
// source and this stays a copy that cannot drift from it.
var rootConjunctRows = [][]string{
	// §9, tri-consonantal.
	{"rř", "p", "ptkdgfţxsšvḑzžcčẓjmnlrwyhļřç"},
	{"l", "p", "ptkdgfţxsšḑcčẓjmnlrwyhļřç"},
	{"m", "p", "dgmnlrwyhļřç"},
	{"ň", "p", "ţlrwyhļřç"},
	{"sšç", "p", "fţsšlrwyhļřç"},
	{"ktcčgdẓjzž", "p", "lrwyhļřç"},
	{"p", "p", "fţsšvlrwyhļřç"},
	{"fvxţḑ", "p", "lrwyhļřç"},
	{"ļ", "p", "lrwyhļřç"},
	{"lrř", "t", "ptkbgfxvmnlrwyhļřç"},
	{"n", "t", "pkbgfvmnlrwyhļř"},
	{"ňsšç", "t", "fvmnlrwyhļřç"},
	{"mpkcčẓjzž", "t", "fvlrwyhļřç"},
	{"tgb", "t", "lrwyhļřç"},
	{"fvxţ", "t", "lrwyhļřç"},
	{"ļ", "t", "lrwyhļřç"},
	{"lrř", "k", "ptkbdfţsšvḑzžcčẓjmnlrwyhřç"},
	{"n", "k", "ptbdfţvḑzžcčẓjmnlrwyhřç"},
	{"mfvţḑ", "k", "fţvlrwyhřç"},
	{"ptkbdsšçcčẓjzž", "k", "fţsšvmnlrwyhřç"},
	{"ļ", "k", "flrwyhřç"},
	{"rř", "b", "tkbdgfţsšvḑzžcčẓjnlrwyhř"},
	{"l", "b", "vḑzžnlrwyř"},
	{"ňsšzžktcčgdẓjfvxţḑç", "b", "vlrwyř"},
	{"m", "b", "lrwyř"},
	{"ļ", "b", "lrwyř"},
	{"b", "b", "vḑlrwyř"},
	{"rř", "d", "pkbdgfvmnlrwyhř"},
	{"l", "d", "vmnlrwyř"},
	{"n", "d", "vmlrwyř"},
	{"mň", "d", "vlrwyř"},
	{"sšfvxţcčẓjḑç", "d", "vlrwyř"},
	{"zž", "d", "vlrwyř"},
	{"ļ", "d", "lrwyř"},
	{"pkbg", "d", "lrwyř"},
	{"d", "d", "vlrwyř"},
	{"rř", "g", "ptbdgfţsšvḑzžcčẓjmnlrwyř"},
	{"l", "g", "vḑmnzžlrwyř"},
	{"nptbdfvţcčẓjḑ", "g", "lrwyř"},
	{"m", "g", "vḑzžlrwyř"},
	{"g", "g", "vḑlrwyř"},
	{"sšzžç", "g", "vḑlrwyř"},
	{"ļ", "g", "lrwyř"},
	{"lrř", "f", "ptkbdgfţxsšḑzžcčẓjmnňlrwyhļřç"},
	{"mň", "f", "ptkbdgfxcčmnňlrwyhļř"},
	{"ptk", "f", "ptkbdgfxmnňlrwyř"},
	{"sšzžxţbdgcčẓjç", "f", "fmnňlrwyř"},
	{"f", "f", "ptkbdgţxsšḑzžcčẓjmnňlrwyhļřç"},
	{"ļ", "f", "flrwyř"},
	{"rlř", "ţ", "ptkbdgfţxsšvcčẓjmnňlrwyhř"},
	{"nň", "ţ", "ptkbdgfţxvcčmnňlrwyhř"},
	{"m", "ţ", "tkdgfţxvcčmnňlrwyhř"},
	{"sšzžç", "ţ", "rw"},
	{"xbg", "ţ", "lrwyř"},
	{"ţ", "ţ", "ptkbdgfxsšvcčẓjmnňlrwyhř"},
	{"pk", "ţ", "ptkbdgfţxsšvcčmnňlrwyř"},
	{"ļ", "ţ", "ţlrwyř"},
	{"rlř", "x", "ptbdfţxvḑcčẓjmnlrw"},
	{"nm", "x", "ptkbdxvmnlrw"},
	{"ptbdcčẓjfvţḑsšzž", "x", "xlrmnw"},
	{"ļ", "x", "xw"},
	{"x", "x", "ptbdfţvḑcčẓjmnlrw"},
	{"rř", "ļ", "ptkbdgfţxļvḑcčẓjmnňrwř"},
	{"ļl", "ļ", "ptkbdgfţxvḑcčẓjmnňrwř"},
	{"mnň", "ļ", "ptkbdgfxļvmnňrwř"},
	{"pt", "ļ", "ptkbdgfxļvmnňrwř"},
	{"cčẓjsšzžfţvḑ", "ļ", "ļ"},
	{"rlřmnňpkf", "s", "ptkbdgfţxsvḑcčjmnňlrwyhř"},
	{"bgv", "s", "ptkfţxscčmnňlrwyř"},
	{"ţ", "s", "ptkbdgfsvmnňlrwyhř"},
	{"s", "s", "ptkbdgfţxvḑcčjmnňlrwyhļř"},
	{"rlřmnňpkf", "š", "ptkbdgfţxšvḑčjmnňlrwyhř"},
	{"bgv", "š", "ptkfţxščwyhlř"},
	{"ţ", "š", "ptkbdgfšvmnňlrwyhř"},
	{"š", "š", "ptkbdgfţxvḑčjmnňlrwyhļř"},
	{"rř", "v", "ptkbdgţxsšvḑzžcčẓjmnňlrwyhļřç"},
	{"l", "v", "bdgvḑzžẓjmnňlrwyřç"},
	{"mň", "v", "vlrwyř"},
	{"ptkdsšzžẓjç", "v", "vlrwyř"},
	{"bg", "v", "bdgvmnlrwyř"},
	{"v", "v", "ptkbdgţxsšḑzžcčẓjmnňlrwyhļřç"},
	{"ļ", "v", "wy"},
	{"rř", "ḑ", "ptkbdgfxvḑcčẓjmnňlrwyhļř"},
	{"l", "ḑ", "bdgḑmnrwyř"},
	{"nmň", "ḑ", "ptkbdgfxvḑmnňlrwyř"},
	{"pk", "ḑ", "ḑrwyř"},
	{"bg", "ḑ", "ptkbdgḑmnlrwyř"},
	{"zž", "ḑ", "ḑrwyř"},
	{"ḑ", "ḑ", "ptkbdgfxvcčẓjmnňlrwyhļř"},
	{"ļ", "ḑ", "wy"},
	{"rřlnmň", "z", "ptkbdgfţxhvḑzẓjmnňlrwyř"},
	{"bgv", "z", "ptkbdgvḑzẓjmnňlrwyhř"},
	{"z", "z", "ptkbdgfţxvḑcčẓjmnňlrwyhļř"},
	{"rřlnmň", "ž", "ptkbdgfţxhvḑžjmnňlrwyř"},
	{"bgv", "ž", "ptkbdgvḑžjmnňlrwyhř"},
	{"ž", "ž", "ptkbdgfţxvḑčjmnňlrwyhļř"},
	{"rřl", "c", "ptkbdgfţxvḑcčjmnňlrwyhļř"},
	{"c", "c", "ptkbdgfţxvḑčjmnňlrwyhļř"},
	{"sx", "c", "wyh"},
	{"rřl", "č", "ptkbdgfţxvḑčmnňlrwyhļř"},
	{"č", "č", "ptkbdgfţxvḑmnňlrwyhļř"},
	{"sš", "č", "wyh"},
	{"rřl", "ẓ", "ptkbdgfţxhvḑẓčjmnňlrwyř"},
	{"ẓ", "ẓ", "ptkbdgfţxvḑmnňlrwyļř"},
	{"rřl", "j", "ptkbdgfţxhvḑjmnňlrwyř"},
	{"j", "j", "ptkbdgfţxvḑmnňlrwyļř"},
	{"rlř", "m", "ptkbdgfţxsšvḑzžcčẓjmnlrwyhļřç"},
	{"ptkbdgfvţḑsšzžxļcčẓjç", "m", "wy"},
	{"m", "m", "ptkbdgfţxsšvḑzžcčẓjnlrwyhļřç"},
	{"rř", "n", "tkdgfţxsšvḑzžmnlrwyhļřç"},
	{"l", "n", "tdkgţḑsšzžlrwyç"},
	{"ptkbdgfvţḑsšzžxļcčẓjç", "n", "wy"},
	{"n", "n", "tkdgfţxsšvḑzžmlrwyhļřç"},
	{"rř", "ň", "ptbdfţsšvḑzžcčẓjmnňlrwhļřç"},
	{"tlfvţḑsšzžļcčẓjç", "ň", "w"},
	{"ň", "ň", "ptbdfţsšvḑzžcčẓjmnlrwhļřç"},
	{"l", "l", "ptkbdgfţxsšvḑzžcčẓjmnňrwyhřç"},
	{"rř", "l", "lwyhř"},
	{"ptkbdgfţxsšvḑzžcčẓjmnňç", "l", "lwy"},
	{"r", "r", "ptkbdgfţxsšvḑzžcčẓjmnňlwyhļç"},
	{"ptkbdgfţxsšvḑzžcčẓjmnňlļç", "r", "r"},
	{"ptkbdgfţx", "r", "wy"},
	{"ř", "ř", "ptkbdgfţxsšvḑzžcčẓjmnňlwyhļç"},
	{"ptkbdgfţsšvḑzžcčẓjmnňlļç", "ř", "ř"},
	{"ptkbdgcčmnňřrl", "h", "mnw"},
	{"ptkbdgcčmnňrl", "h", "r"},
	{"ptkmnňrlř", "ç", "ptkbdgfvcčmnňlrwřç"},
	{"f", "ç", "ptkmnçw"},
	{"ç", "ç", "ptkbdgfvcčmnňlrwř"},
	// §10, tetra-consonantal.
	{"rřl", "m", "p", "mnlrwyhļřç"},
	{"rř", "ň", "p", "ţlrwyļřhç"},
	{"rřl", "pktcčgdẓjzž", "p", "fţsšlrwyļřhç"},
	{"ptkrřlçmnň", "ç", "p", "fţlrwyļřhç"},
	{"f", "ç", "p", "lrwyļřhç"},
	{"spkrřlmnň", "sš", "p", "fţsšlrwyļřhç"},
	{"fţ", "sš", "p", "fţsšlrwyļřhç"},
	{"m", "zžfx", "p", "fţlrwyļřhç"},
	{"n", "ktzžx", "p", "fţlrwyļřhç"},
	{"ň", "tzžf", "p", "fţlrwyļřhç"},
	{"mnň", "ţ", "p", "fţlsšrwyļřhç"},
	{"rř", "fvxţḑ", "p", "lrwyļřhç"},
	{"l", "fxţ", "p", "lrwyļřhç"},
	{"tmnrř", "ļ", "p", "lrwyřhç"},
	{"zbgv", "z", "p", "flrwyļřhç"},
	{"žbgv", "ž", "p", "flrwyļřhç"},
	{"pk", "fţ", "p", "lrwyļřhç"},
	{"r", "r", "p", "fţsšlrwyļhç"},
	{"ř", "ř", "p", "fţsšlwyļřhç"},
	{"l", "l", "p", "fţsšlrwyļřhç"},
	{"m", "m", "p", "ţsšlrwyļřhç"},
	{"ň", "ň", "p", "fţsšlrwyļřhç"},
	{"rř", "n", "t", "pkbgfvmnlrwyhļřç"},
	{"rř", "ň", "t", "fvmnlrwyļřhç"},
	{"rřl", "m", "t", "fvlrwyļřhç"},
	{"ptkrřlçmnň", "ç", "t", "fvmnlrwyļřhç"},
	{"f", "ç", "t", "lrwyļřhç"},
	{"fţspkrřlmnň", "s", "t", "fvmnlrwyļřhç"},
	{"fţšpkrřlmnň", "š", "t", "fvmnlrwyļřhç"},
	{"rř", "pktcčgbẓjzžfvxţ", "t", "lrwyļřhç"},
	{"l", "pktcčzž", "t", "lrwyļřhç"},
	{"m", "zžpfxţm", "t", "lrwyļřhç"},
	{"n", "zžkxţn", "t", "lrwyļřhç"},
	{"ň", "zžfţň", "t", "lrwyļřhç"},
	{"l", "fxţ", "t", "lrwyļřhç"},
	{"pmnrřļ", "ļ", "t", "lrwyřhç"},
	{"t", "ļ", "t", "rwyřhç"},
	{"zbgv", "z", "t", "flrwyļřhç"},
	{"žbgv", "ž", "t", "flrwyļřhç"},
	{"pk", "fţ", "t", "lrwyļřhç"},
	{"r", "r", "t", "pkbgfvlrwyļhç"},
	{"ř", "ř", "t", "pkbgfvlwyļřhç"},
	{"l", "l", "t", "kgfvlrwyļřhç"},
	{"m", "m", "t", "kgfvmnlrwyhļřç"},
	{"n", "n", "t", "kgfvmnlrwyhļřç"},
	{"ň", "ň", "t", "kgfvmnlrwyhļřç"},
	{"rř", "n", "k", "ptbdfţvḑcčẓjmnlrwyhřç"},
	{"rřl", "pmfvţ", "k", "fţsšlrwyřhç"},
	{"nrřl", "t", "k", "fţvlrwyřhç"},
	{"m", "fţm", "k", "fţvsšmnlrwyřhç"},
	{"n", "ţn", "k", "fţvsšmnlrwyřhç"},
	{"ň", "fţň", "k", "fţvsšmnlrwyřhç"},
	{"ptkrřlçmnň", "ç", "k", "fţvmnlrwyřhç"},
	{"f", "ç", "k", "vlrwyřhç"},
	{"pkfţmnňrřl", "sš", "k", "fţvmnlrwyřhç"},
	{"rřl", "kbdḑcčẓjzž", "k", "fţvlrwyřhç"},
	{"rřl", "ptbd", "k", "sš"},
	{"s", "s", "k", "fţvmnlrwyřhç"},
	{"š", "š", "k", "fţvmnlrwyřhç"},
	{"zbgmnňv", "z", "k", "fţvmnlrwyřhç"},
	{"žbgmnňv", "ž", "k", "fţvmnlrwyřhç"},
	{"tmnrř", "ļ", "k", "fţvmnlrwyřhç"},
	{"pk", "fţ", "k", "fţvmnlrwyřhç"},
	{"r", "r", "k", "fţvḑsšmnlrwyhřç"},
	{"ř", "ř", "k", "fţvḑsšmnlrwyhřç"},
	{"l", "l", "k", "fţvḑsšmnlrwyhřç"},
	{"m", "m", "k", "fţvḑsšmnlrwyhřç"},
	{"n", "n", "k", "fţvḑmnlrwyhřç"},
	{"rřl", "msšzžktcčẓjfvxţ", "b", "lrwyř"},
	{"rř", "ňbgdḑ", "b", "lrwyř"},
	{"m", "sšzžfvxţ", "b", "lrwyř"},
	{"n", "ktdḑsšzžxţ", "b", "lrwyř"},
	{"pk", "fţ", "b", "lrwyř"},
	{"spkfţ", "s", "b", "lrwyř"},
	{"špkfţ", "š", "b", "lrwyř"},
	{"zbgv", "z", "b", "vlrwyř"},
	{"žbgv", "ž", "b", "vlrwyř"},
	{"ptkrřlmnň", "ç", "b", "lrwyř"},
	{"tmnrř", "ļ", "b", "lrwyř"},
	{"dgv", "v", "b", "lrwyř"},
	{"bg", "ḑ", "b", "vlrwyř"},
	{"r", "r", "b", "vḑlrwyř"},
	{"ř", "ř", "b", "vḑlrwyř"},
	{"l", "l", "b", "vḑlrwyř"},
	{"m", "m", "b", "ḑlrwyř"},
	{"ň", "ň", "b", "vḑlrwyř"},
	{"rř", "n", "d", "vmlrwyř"},
	{"rř", "ň", "d", "vlrwyř"},
	{"rř", "bg", "d", "vlrwyř"},
	{"rřl", "mzžẓj", "d", "vlrwyř"},
	{"rřl", "pkdsškcčfvxţḑ", "d", "lrwyř"},
	{"m", "psšfvxţzžḑ", "d", "lrwyř"},
	{"n", "ksšxţzžḑ", "d", "lrwyř"},
	{"ň", "sšfvţzžḑ", "d", "lrwyř"},
	{"fpk", "f", "d", "lrwyř"},
	{"ţpk", "ţ", "d", "lrwyř"},
	{"spkfţ", "s", "d", "lrwyř"},
	{"špkfţ", "š", "d", "lrwyř"},
	{"zbgv", "z", "d", "lrwyř"},
	{"žbgv", "ž", "d", "lrwyř"},
	{"ptkrřlmnň", "ç", "d", "lrwyř"},
	{"tmnrř", "ļ", "d", "lrwyř"},
	{"bgv", "v", "d", "lrwyř"},
	{"bg", "ḑ", "d", "vlrwyř"},
	{"r", "r", "d", "vlrwyř"},
	{"ř", "ř", "d", "vlrwyř"},
	{"l", "l", "d", "vlrwyř"},
	{"m", "m", "d", "vlrwyř"},
	{"n", "n", "d", "vlrwyř"},
	{"ň", "ň", "d", "vlrwyř"},
	{"rřl", "m", "g", "vḑzžlrwyř"},
	{"rř", "n", "g", "lrwyř"},
	{"rřl", "ptbdgfvţcčẓjḑç", "g", "lrwyř"},
	{"rřlmnň", "sšzž", "g", "vḑlmnrwyř"},
	{"m", "ptfvţḑ", "g", "lrwyř"},
	{"n", "tdţḑ", "g", "lrwyř"},
	{"pk", "fţ", "g", "lrwyř"},
	{"spkfţ", "s", "g", "lrwyř"},
	{"špkfţ", "š", "g", "lrwyř"},
	{"zbgv", "z", "g", "vḑzžmnlrwyř"},
	{"žbgv", "ž", "g", "vḑžmnlrwyř"},
	{"tmnrř", "ļ", "g", "lrwyř"},
	{"ptkrřlmnň", "ç", "g", "lrwyř"},
	{"bg", "ḑ", "g", "vlrwyř"},
	{"bdv", "v", "g", "vḑlrwyř"},
	{"r", "r", "g", "vḑlrwyř"},
	{"ř", "ř", "g", "vḑlrwyř"},
	{"l", "l", "g", "vḑlrwyř"},
	{"m", "m", "g", "vḑlrwyř"},
	{"n", "n", "g", "vḑlrwyř"},
	{"rřln", "k", "f", "ptkbdgfmnňlrwyř"},
	{"rřl", "p", "f", "tkbdgfmnňlrwyř"},
	{"rřlmnň", "tţsšzžç", "f", "mnňlrwyř"},
	{"m", "k", "f", "lrwyř"},
	{"rřlmň", "f", "f", "ptkbdgţxsšḑzžcčẓjmnňlrwyļř"},
	{"rřlmn", "x", "f", "lrwyř"},
	{"rřl", "bdgcčẓj", "f", "mnňlrwyř"},
	{"spkfţ", "s", "f", "mnňlrwyř"},
	{"špkfţ", "š", "f", "mnňlrwyř"},
	{"zbgv", "z", "f", "mnňlrwyř"},
	{"žbgv", "ž", "f", "mnňlrwyř"},
	{"tmnrř", "ļ", "f", "lrwyř"},
	{"pkţ", "ţ", "f", "lrwyř"},
	{"r", "r", "f", "ptkţxsšzžmnňlrwyř"},
	{"ř", "ř", "f", "ptkţxsšzžmnňlrwyř"},
	{"l", "l", "f", "ptkţxsšzžmnňlrwyř"},
	{"m", "m", "f", "ptkţxsšzžmnňlrwyř"},
	{"ň", "ň", "f", "ptkţxsšzžmnňlrwyř"},
	{"rřl", "nň", "ţ", "ptkbdgfţxvcčmnňlrwyhř"},
	{"rřl", "m", "ţ", "tkdgfţxvcčmnňlrwyř"},
	{"rřl", "p", "ţ", "tkdgfţxvmnňlrwyř"},
	{"rřl", "k", "ţ", "ptkbdgfţxvmnňlrwyř"},
	{"pkrřlmnň", "ţ", "ţ", "ptkbdgfxsšvcčẓjmnňlrwyř"},
	{"rřln", "x", "ţ", "lrwyř"},
	{"rřl", "bg", "ţ", "lrwyř"},
	{"rřlmnň", "sšzž", "ţ", "rw"},
	{"spkfţ", "s", "ţ", "rw"},
	{"špkfţ", "š", "ţ", "rw"},
	{"zbgv", "z", "ţ", "rw"},
	{"žbgv", "ž", "ţ", "rw"},
	{"sšzžmn", "pk", "ţ", "lrwyř"},
	{"r", "r", "ţ", "ptkxsšvcčẓjmnňlrwyř"},
	{"ř", "ř", "ţ", "ptkxsšvcčẓjmnňlrwyř"},
	{"l", "l", "ţ", "ptkxsšvcčẓjmnňlrwyř"},
	{"m", "m", "ţ", "ptkxsšvcčẓjmnňlrwyř"},
	{"n", "n", "ţ", "ptkxsšvcčẓjmnňlrwyř"},
	{"ň", "ň", "ţ", "ptkxsšvcčẓjmnňlrwyř"},
	{"rř", "mn", "x", "ptkbdxvmnlrw"},
	{"rřln", "x", "x", "ptkbdxvmnlrw"},
	{"rřlm", "ptfvţḑ", "x", "xmnlrw"},
	{"rř", "bd", "x", "xmnlrw"},
	{"n", "ţḑ", "x", "xmnlrw"},
	{"spkfrřlmnň", "s", "x", "xmnlrw"},
	{"zbgvrřlmnň", "z", "x", "xmnlrw"},
	{"žbgvrřlmnň", "ž", "x", "xmnlrw"},
	{"pk", "fţ", "x", "xmnlrw"},
	{"r", "r", "x", "ptmnlrw"},
	{"ř", "ř", "x", "ptmnlrw"},
	{"l", "l", "x", "ptmnlrw"},
	{"m", "m", "x", "ptmnlrw"},
	{"n", "n", "x", "ptmnlrw"},
	{"pkfs", "s", "l", "wy"},
	{"pkfš", "š", "l", "wy"},
	{"bgvz", "z", "l", "wy"},
	{"bgvž", "ž", "l", "wy"},
	{"r", "ļ", "ļ", "ptkbdgfţxvḑcčẓjmnňrwř"},
	{"mnň", "ļ", "ļ", "ptkbdgfxvmnňrwř"},
	{"rřln", "t", "ļ", "ptkbdgfxvmnňrwř"},
	{"rřl", "cčẓjsšzžfţv", "ļ", "ļ"},
	{"mnň", "sšzžţ", "ļ", "ļ"},
	{"mň", "f", "ļ", "ļ"},
	{"rřl", "ptm", "ļ", "ļ"},
	{"rř", "mnňpkf", "s", "ptkbdgfţxsvḑcčjmnňlrwyhř"},
	{"l", "mpkf", "s", "ptkbdgfţxsvḑcčjmnňlrwyhř"},
	{"m", "f", "s", "ptkbdgfţxsvḑcčjmnňlrwyhř"},
	{"pkrřlmnň", "ţ", "s", "ptkbdgfsvmnňlrwyhř"},
	{"rř", "bgv", "s", "ptkfţxscč"},
	{"pkrřlmnň", "s", "s", "ptkbdgfţxvḑcčjmnňlrwyļř"},
	{"r", "r", "s", "ptkbdgfţxvḑcčjmnňlrwyhř"},
	{"ř", "ř", "s", "ptkbdgfţxvḑcčjmnňlrwyhř"},
	{"l", "l", "s", "ptkbdgfţxvḑcčjmnňlrwyhř"},
	{"m", "m", "s", "ptkbdgfţxvḑcčjmnňlrwyhř"},
	{"n", "n", "s", "ptkbdgfţxvḑcčjmnňlrwyhř"},
	{"ň", "ň", "s", "ptkbdgfţxvḑcčjmnňlrwyhř"},
	{"rř", "mnňpkf", "š", "ptkbdgfţxšvḑčjmnňlrwyhř"},
	{"l", "mpkf", "š", "ptkbdgfţxšvḑčjmnňlrwyhř"},
	{"m", "f", "š", "ptkbdgfţxšvḑčjmnňlrwyhř"},
	{"pkrřlmnň", "ţ", "š", "ptkbdgfšvmnňlrwyhř"},
	{"rř", "bgv", "š", "ptkfţxščwyhlř"},
	{"pkrřlmnň", "š", "š", "ptkbdgfţxvḑčjmnňlrwyļř"},
	{"r", "r", "š", "ptkbdgfţxvḑčjmnňlrwyļř"},
	{"ř", "ř", "š", "ptkbdgfţxvḑčjmnňlrwyļř"},
	{"l", "l", "š", "ptkbdgfţxvḑčjmnňlrwyļř"},
	{"m", "m", "š", "ptkbdgfţxvḑčjmnňlrwyļř"},
	{"n", "n", "š", "ptkbdgfţxvḑčjmnňlrwyļř"},
	{"ň", "ň", "š", "ptkbdgfţxvḑčjmnňlrwyļř"},
	{"bgvz", "z", "v", "vlrwyř"},
	{"bgvž", "ž", "v", "vlrwyř"},
	{"mnrřl", "tkdţsšzž", "v", "vlrwyř"},
	{"ň", "tdţsšzž", "v", "vlrwyř"},
	{"rř", "mňg", "v", "vlrwyř"},
	{"rřl", "mpzžẓjb", "v", "vlrwyř"},
	{"rřlmň", "v", "v", "ptkbdgţxsšḑzžcčẓjmnňlrwyļř"},
	{"pkţ", "ţ", "v", "vlrwyř"},
	{"pkfmnň", "sš", "v", "vlrwyř"},
	{"rřmnň", "ļ", "v", "wy"},
	{"r", "r", "v", "bdgţxsšḑzžcčẓjmnňlrwyļř"},
	{"ř", "ř", "v", "bdgţxsšḑzžcčẓjmnňlrwyļř"},
	{"l", "l", "v", "bdgţxsšḑzžcčẓjmnňlrwyļř"},
	{"m", "m", "v", "bdgţxsšḑzžcčẓjmnňlrwyļř"},
	{"ň", "ň", "v", "bdgţxsšḑzžcčẓjmnňlrwyļř"},
	{"rřl", "pk", "ḑ", "ḑrwyř"},
	{"rř", "bgmn", "ḑ", "bdgḑmnlrwyř"},
	{"l", "bgm", "ḑ", "bdgḑmnlrwyř"},
	{"rřlmnň", "zž", "ḑ", "ḑrwyř"},
	{"rřl", "ḑ", "ḑ", "ptkbdgfxvcčẓjmnňlrwyļř"},
	{"ļrř", "ļ", "ḑ", "wy"},
	{"r", "r", "ḑ", "ptkbdgfxvcčẓjmnňlrwyļř"},
	{"ř", "ř", "ḑ", "ptkbdgfxvcčẓjmnňlrwyļř"},
	{"l", "l", "ḑ", "ptkbdgfxvcčẓjmnňlrwyļř"},
	{"m", "m", "ḑ", "ptkbdgfxvcčẓjmnňlrwyļř"},
	{"n", "n", "ḑ", "ptkbdgfxvcčẓjmnňlrwyļř"},
	{"ň", "ň", "ḑ", "ptkbdgfxvcčẓjmnňlrwyļř"},
	{"rř", "nň", "z", "ptkbdgfţxvḑzjmnňlrwyř"},
	{"rřl", "m", "z", "ptkbdgfţxvḑzjmnňlrwyř"},
	{"rřl", "bgv", "z", "bdgvḑzjmnňlrwyhř"},
	{"rřlmnň", "z", "z", "ptkbdgfţxvḑjmnňlrwyļř"},
	{"bg", "z", "z", "ptkbdgvxḑjmnňlrwyř"},
	{"r", "r", "z", "ptkbdgvxḑjmnňlrwyř"},
	{"ř", "ř", "z", "ptkbdgvxḑjmnňlrwyř"},
	{"l", "l", "z", "ptkbdgvxḑjmnňlrwyř"},
	{"m", "m", "z", "ptkbdgvxḑjmnňlrwyř"},
	{"n", "n", "z", "ptkbdgvxḑjmnňlrwyř"},
	{"ň", "ň", "z", "ptkbdgvxḑjmnňlrwyř"},
	{"rř", "nň", "ž", "ptkbdgfţxvḑžjmnňlrwyř"},
	{"rřl", "m", "ž", "ptkbdgfţxvḑžjmnňlrwyř"},
	{"rř", "bg", "ž", "bdgvḑžjmnňlrwyhř"},
	{"rřl", "v", "ž", "bdgvḑžjmnňlrwyhř"},
	{"rřlmnň", "ž", "ž", "ptkbdgfţxvḑjmnňlrwyļř"},
	{"bg", "ž", "ž", "ptkbdgxvḑjmnňlrwyř"},
	{"r", "r", "ž", "ptkbdgxvḑjmnňlrwyř"},
	{"ř", "ř", "ž", "ptkbdgxvḑjmnňlrwyř"},
	{"l", "l", "ž", "ptkbdgxvḑjmnňlrwyř"},
	{"m", "m", "ž", "ptkbdgxvḑjmnňlrwyř"},
	{"n", "n", "ž", "ptkbdgxvḑjmnňlrwyř"},
	{"ň", "ň", "ž", "ptkbdgxvḑjmnňlrwyř"},
	{"ptkrřlçmnň", "ç", "c", "mnňhlrřwy"},
	{"ptkrřlmnň", "ţ", "c", "mnňwy"},
	{"mnňļ", "ļ", "c", "mnňwy"},
	{"r", "r", "c", "mnňhlrřwy"},
	{"ř", "ř", "c", "mnňhlrřwy"},
	{"l", "l", "c", "mnňhlrřwy"},
	{"m", "m", "c", "mnňhlrřwy"},
	{"ň", "ň", "c", "mnňhlrřwy"},
	{"ptkrřlçmnň", "ç", "č", "mnňhlrřwy"},
	{"ptkrřlmnň", "ţ", "č", "mnňwy"},
	{"mnňļ", "ļ", "č", "mnňwy"},
	{"r", "r", "č", "mnňhlrřwy"},
	{"ř", "ř", "č", "mnňhlrřwy"},
	{"l", "l", "č", "mnňhlrřwy"},
	{"m", "m", "č", "mnňhlrřwy"},
	{"ň", "ň", "č", "mnňhlrřwy"},
	{"r", "r", "ẓ", "mnňlrřwy"},
	{"ř", "ř", "ẓ", "mnňlrřwy"},
	{"l", "l", "ẓ", "mnňlrřwy"},
	{"r", "r", "j", "mnňlrřwy"},
	{"ř", "ř", "j", "mnňlrřwy"},
	{"l", "l", "j", "mnňlrřwy"},
	{"rřl", "m", "m", "ptkbdgfţxsšvḑzžcčẓjnlrwyhļřç"},
	{"rř", "ptkbdgfvţḑsšzžxļcčẓjç", "m", "lrřwy"},
	{"l", "ptkfţsšzžxļcčẓjç", "m", "lrřwy"},
	{"m", "fvţḑsšzžxļç", "m", "lrřwy"},
	{"n", "tkdţḑsšzžxļç", "m", "lrřwy"},
	{"ň", "tdţḑsšzžļç", "m", "lrřwy"},
	{"spkfţ", "s", "m", "lrřwy"},
	{"špkfţ", "š", "m", "lrřwy"},
	{"zbgv", "z", "m", "lrřwy"},
	{"žbgv", "ž", "m", "lrřwy"},
	{"ptkç", "ç", "m", "lrřwy"},
	{"pkţ", "ţ", "m", "lrřwy"},
	{"çsšf", "t", "m", "wy"},
	{"çsš", "k", "m", "wy"},
	{"ptļ", "ļ", "m", "wy"},
	{"r", "r", "m", "ptkbdgfţxsšvḑzžcčẓjnlrwyhļř"},
	{"ř", "ř", "m", "ptkbdgfţxsšvḑzžcčẓjnlrwyhļř"},
	{"l", "l", "m", "ptkbdgfţxsšvḑzžcčẓjnlrwyhļř"},
	{"rřl", "n", "n", "tkdgfţxsšvḑzžmlrwyhļřç"},
	{"rř", "ptkbdgfvţḑsšzžxļcčẓjç", "n", "wy"},
	{"l", "ptkfţsšzžxļcčẓjç", "n", "wy"},
	{"m", "fvţsšzžxļç", "n", "wy"},
	{"n", "tkdţḑsšzžxļç", "n", "wy"},
	{"ň", "tţḑsšzžļç", "n", "wy"},
	{"spkfţ", "s", "n", "wy"},
	{"špkfţ", "š", "n", "wy"},
	{"zbgv", "z", "n", "wy"},
	{"žbgv", "ž", "n", "wy"},
	{"çsšf", "t", "n", "wy"},
	{"çsš", "k", "n", "wy"},
	{"ptkmnňrřlç", "ç", "n", "wy"},
	{"ptmnňrř", "ļ", "n", "wy"},
	{"pkţ", "ţ", "n", "wy"},
	{"r", "r", "n", "tkdgfţxsšvḑzžmlrwyhļř"},
	{"ř", "ř", "n", "tkdgfţxsšvḑzžmlrwyhļř"},
	{"l", "l", "n", "lrwyļř"},
	{"rř", "ň", "ň", "ptbdfţsšvḑzžcčẓjmnlrwhļř"},
	{"srřl", "s", "ň", "w"},
	{"šrřl", "š", "ň", "w"},
	{"zrřl", "z", "ň", "w"},
	{"žrřl", "ž", "ň", "w"},
	{"ptkmnňrřlç", "ç", "ň", "w"},
	{"pkm", "f", "ň", "w"},
	{"pkn", "ţ", "ň", "w"},
	{"ptmnňrř", "ļ", "ň", "w"},
	{"pkţ", "ţ", "ň", "w"},
	{"r", "r", "ň", "ptbdfţsšvḑzžcčẓjmnlrwhļř"},
	{"ř", "ř", "ň", "ptbdfţsšvḑzžcčẓjmnlrwhļř"},
	{"l", "l", "ň", "w"},
	{"rřlm", "ptkcč", "h", "w"},
	{"n", "tk", "h", "w"},
	{"ň", "ptcč", "h", "w"},
	{"rřl", "mnň", "h", "wr"},
	{"r", "lr", "h", "mnw"},
	{"l", "l", "h", "mnw"},
	{"ř", "ř", "h", "mnw"},
	{"m", "m", "h", "w"},
	{"n", "n", "h", "w"},
	{"ň", "ň", "h", "w"},
	{"rř", "ptkmnň", "ç", "ptkbdgfvcčmnňlrwřç"},
	{"l", "ptkm", "ç", "ptkbdgfvcčmnňlrwřç"},
	{"mnňlrř", "ç", "ç", "ptkbdgfvcčmnňlrwř"},
	{"mlrř", "f", "ç", "ptkbdgfvcčmnňlrwřç"},
	{"r", "r", "ç", "ptkbdgfvcčmnňlrwř"},
	{"ř", "ř", "ç", "ptkbdgfvcčmnňlrwř"},
	{"l", "l", "ç", "ptkbdgfvcčmnňlrwř"},
	{"m", "m", "ç", "ptkbdgfvcčmnňlrwř"},
	{"n", "n", "ç", "ptkbdgfvcčmnňlrwř"},
	{"ň", "ň", "ç", "ptkbdgfvcčmnňlrwř"},
	// §11, penta-consonantal.
	{"lrř", "pkfţ", "sš", "ptkbdg", "lrřwy"},
	{"lrř", "pkfţ", "sš", "ptk", "ţçh"},
	{"lrř", "pkfţ", "sš", "bg", "ḑv"},
	{"lrř", "pkf", "sš", "mn", "wy"},
	{"lrř", "pkf", "sš", "ň", "w"},
	{"lrř", "pk", "fţ", "ptkbdg", "lrřwy"},
	{"lrř", "pk", "fţ", "ptk", "h"},
	{"lrř", "pkf", "sš", "fţ", "lrřwy"},
	{"lrmnň", "sšç", "pk", "f", "lrřwy"},
	{"lrř", "m", "sšzžç", "ţf", "lrřwy"},
	{"lrř", "m", "sšzžţfç", "ptkbdg", "lrřwy"},
	{"lrř", "m", "sšzžţfç", "ptk", "hf"},
	{"lrř", "m", "sšzžç", "pk", "ţ"},
	{"l", "m", "sšzžç", "pt", "ļ"},
	{"lrř", "pt", "ļ", "ptkbdg", "lrřwy"},
	{"lrř", "pt", "ļ", "ptk", "h"},
	{"lrř", "ptk", "ç", "ptkbdgf", "lrřwy"},
	{"lrř", "ptk", "ç", "ptk", "h"},
	{"lrř", "v", "zž", "ptkbdg", "lrřwy"},
	{"lrř", "v", "zž", "ptk", "h"},
	{"lrř", "v", "zž", "pk", "ţf"},
	{"rř", "nň", "sšzžţç", "ptkbdg", "lrřwy"},
	{"rř", "nň", "sšzžţç", "ptk", "h"},
	{"rř", "ň", "f", "ptkbdg", "lrřwy"},
	{"rř", "ň", "f", "ptk", "h"},
	{"rř", "nň", "sšzžç", "pk", "ţf"},
	{"rř", "mnň", "sšzžç", "pt", "ļ"},
	{"rř", "nň", "sšzžç", "ţf", "lrřwy"},
	{"rř", "nň", "ḑ", "bg", "lrřwy"},
	{"rř", "n", "t", "pk", "lrřhwy"},
	{"rř", "n", "k", "pt", "lrřhwy"},
	{"pkfmnňlrř", "s", "s", "ptkf", "lrřhwy"},
	{"pkfmnňlrř", "s", "s", "mn", "wy"},
	{"pkfmnňlrř", "s", "s", "ň", "w"},
	{"pkfmnňlrř", "š", "š", "ptkf", "lrřhwy"},
	{"pkfmnňlrř", "š", "š", "mn", "wy"},
	{"pkfmnňlrř", "š", "š", "ň", "w"},
	{"pt", "sšç", "ptk", "h", "w"},
	{"pk", "ţ", "ptk", "h", "w"},
	{"lrř", "pkm", "s", "s", "ptkmnňlrřwy"},
	{"rř", "nň", "s", "s", "ptkmnňlrřwy"},
	{"lrř", "pkm", "š", "š", "ptkmnňlrřwy"},
	{"rř", "nň", "š", "š", "ptkmnňlrřwy"},
	{"lrř", "ţf", "pk", "s", "s"},
	{"lrř", "mn", "k", "s", "s"},
	{"lrř", "ţf", "pk", "š", "š"},
	{"lrř", "mn", "k", "š", "š"},
	{"pkmnňlrř", "ç", "ç", "ptk", "lrřhwy"},
	{"pkmnňlrř", "ç", "ç", "mn", "wy"},
	{"lrř", "ptkm", "ç", "ç", "ptkmnňlrřw"},
	{"rř", "nň", "ç", "ç", "ptkmnňlrřw"},
	{"lrř", "ţ", "pk", "ç", "ç"},
	{"lrř", "f", "ptk", "ç", "ç"},
	{"lrř", "mn", "tk", "ç", "ç"},
	{"m", "m", "sšçfţzžvḑ", "ptk", "lrřhwy"},
	{"n", "n", "sšçţzžḑ", "ptk", "lrřhwy"},
	{"ň", "ň", "sšçfţzžvḑ", "ptk", "lrřhwy"},
	{"m", "m", "sšçfţzžvḑ", "bdg", "lrřwy"},
	{"n", "n", "sšçţzžḑ", "bdg", "lrřwy"},
	{"ň", "ň", "sšçfţzžvḑ", "bdg", "lrřwy"},
	{"m", "m", "sšzž", "v", "lrřwy"},
	{"n", "n", "sšzž", "v", "lrřwy"},
	{"ň", "ň", "sšzž", "v", "lrřwy"},
	{"lrř", "m", "m", "k", "sšçlrřhwy"},
	{"lrř", "m", "m", "pt", "ļlrřhwy"},
	{"lrř", "m", "m", "sšçfţ", "ptklrřwy"},
	{"lrř", "m", "m", "sšçfţ", "mnňx"},
	{"lrř", "m", "m", "sšç", "fţv"},
	{"lrř", "m", "m", "f", "ţ"},
	{"lrř", "n", "n", "k", "lrřhwy"},
	{"lrř", "n", "n", "t", "ļlrřhwy"},
	{"lrř", "n", "n", "sšçţ", "ptklrřwy"},
	{"lrř", "n", "n", "sšçţ", "mnňfvx"},
	{"lrř", "n", "n", "sšç", "ţ"},
	{"lrř", "ň", "ň", "pt", "ļlrřhwy"},
	{"lrř", "ň", "ň", "sšçfţ", "ptklrřwy"},
	{"lrř", "ň", "ň", "sšçfţ", "mnňx"},
	{"lrř", "ň", "ň", "sšç", "fţv"},
	{"lrř", "ň", "ň", "f", "ţ"},
	{"l", "l", "sšçfţ", "ptk", "ļlrřhwy"},
	{"l", "l", "sšçfţ", "k", "lrřhwy"},
	{"l", "l", "sšçfţ", "mn", "wy"},
	{"l", "l", "sšçfţ", "ň", "w"},
	{"l", "l", "sšçfţ", "bdg", "lrřwy"},
	{"l", "l", "m", "sšçfţ", "ptkbdglrřwy"},
	{"l", "l", "m", "sšç", "fţv"},
	{"r", "r", "sšçfţ", "ptk", "ļlrřhwy"},
	{"r", "r", "sšçfţ", "k", "lrřhwy"},
	{"r", "r", "sšçfţ", "mnň", "wy"},
	{"r", "r", "mnň", "sšçfţ", "ptkbdglrřwy"},
	{"r", "r", "mnň", "sšç", "fţv"},
	{"ř", "ř", "sšçfţ", "ptk", "ļlrřhwy"},
	{"ř", "ř", "sšçfţ", "k", "lrřhwy"},
	{"ř", "ř", "sšçfţ", "mnň", "wy"},
	{"ř", "ř", "mnň", "sšçfţ", "ptkbdglrřwy"},
	{"ř", "ř", "mnň", "sšç", "fţv"},
	{"lrř", "bgv", "zž", "ptkbdg", "lrřwy"},
	{"lrř", "bgv", "zž", "ptk", "h"},
	{"lrř", "bg", "vḑ", "bdg", "lrřwy"},
	{"lrř", "bgv", "zž", "v", "lrřwy"},
	{"lrř", "mnň", "zž", "bg", "vḑ"},
	{"lrř", "mnň", "zž", "d", "v"},
	{"lrř", "mň", "v", "bdg", "lrřwy"},
	{"lrř", "n", "ḑ", "bdg", "lrřwy"},
	{"bgvmnňlrř", "z", "z", "ptk", "lrřhwy"},
	{"bgvmnňlrř", "z", "z", "bdgfv", "lrřwy"},
	{"bgvmnňlrř", "z", "z", "mn", "wy"},
	{"bgvmnňlrř", "z", "z", "ň", "w"},
	{"bgvmnňlrř", "ž", "ž", "ptk", "lrřhwy"},
	{"bgvmnňlrř", "ž", "ž", "bdgfv", "lrřwy"},
	{"bgvmnňlrř", "ž", "ž", "mn", "wy"},
	{"bgvmnňlrř", "ž", "ž", "ň", "w"},
	{"lrř", "bgm", "z", "z", "ptkbdgmnňlrřwy"},
	{"rř", "nň", "z", "z", "ptkbdgmnňlrřwy"},
	{"lrř", "bgm", "ž", "ž", "ptkbdgmnňlrřwy"},
	{"rř", "nň", "ž", "ž", "ptkbdgmnňlrřwy"},
	{"lrř", "m", "m", "bg", "zžlrřwy"},
	{"lrř", "m", "m", "zžvḑ", "ptkbdglrřwy"},
	{"lrř", "m", "m", "zž", "mnňxfţvḑ"},
	{"lrř", "m", "m", "v", "mnňxţḑ"},
	{"lrř", "m", "m", "ḑ", "mnň"},
	{"lrř", "n", "n", "g", "lrřwy"},
	{"lrř", "n", "n", "zžvḑ", "ptkbdglrřwy"},
	{"lrř", "n", "n", "zž", "mnňxfţvḑ"},
	{"lrř", "n", "n", "ḑ", "mnň"},
	{"lrř", "ň", "ň", "bd", "lrřwy"},
	{"lrř", "ň", "ň", "zžvḑ", "ptkbdglrřwy"},
	{"lrř", "ň", "ň", "zž", "mnňxfţvḑ"},
	{"lrř", "ň", "ň", "v", "mnňxţḑ"},
	{"lrř", "ň", "ň", "ḑ", "mnň"},
	{"l", "l", "zžvḑ", "ptk", "ļlrřhwy"},
	{"l", "l", "zžvḑ", "k", "lrřhwy"},
	{"l", "l", "zžvḑ", "mn", "wy"},
	{"l", "l", "zžvḑ", "ň", "w"},
	{"l", "l", "zžvḑ", "bdg", "lrřwy"},
	{"l", "l", "m", "zžvḑ", "ptkbdglrřwy"},
	{"l", "l", "m", "zž", "fţvḑ"},
	{"r", "r", "zžvḑ", "ptk", "ļlrřhwy"},
	{"r", "r", "zžvḑ", "k", "lrřhwy"},
	{"r", "r", "zžvḑ", "mn", "wy"},
}

// RootConjunctLegal reports whether a consonant conjunct may be a C_R
// root or a C_S affix.
//
// This is a narrower question than ClusterLegal, and a different one.
// ClusterLegal judges whether a conjunct can be said, by §§2-7, which
// are rules about adjacent pairs. §§8-11 enumerate which conjuncts a
// root or an affix may be, and the two do not coincide above two
// consonants: "fbm" passes every pair rule — "fb" and "bm" are each
// permissible per §8 — and appears in no §9 row, because the row for
// medial b whose initials include f permits only vlrwyř third. A
// speaker asked to say it reported it impossible.
//
// Scope is the whole of why this is a separate predicate rather than
// part of ClusterLegal. §9's title is "Permissible Tri-Consonantal
// Conjuncts Which Can Be Roots or Affixes", so it governs roots and
// affixes and not every triple in a word: a Slot VI C_A complex is
// tri-consonantal and answers to §4.3 and §4.4 instead. Folding this
// into ClusterLegal would reject legitimate C_A forms and stop the
// renderer round-tripping its own output.
//
// One and two consonants are left to ClusterLegal. §8's grid of
// bi-consonantal forms is derived from §§2-7 rather than independent of
// them, which TestSection8GridMatchesRules shows cell for cell, so
// there is nothing here it would add. Six or more is not enumerated by
// any section and no root has that many.
func RootConjunctLegal(conjunct string) bool {
	rs := []rune(conjunct)
	if len(rs) < 3 {
		return ClusterLegal(conjunct)
	}
	for _, row := range rootConjunctRows {
		if len(row) != len(rs) {
			continue
		}
		if rowAdmits(row, rs) {
			return true
		}
	}
	return false
}

func rowAdmits(row []string, rs []rune) bool {
	for i, set := range row {
		if !strings.ContainsRune(set, rs[i]) {
			return false
		}
	}
	return true
}
